name = "bale-checker"
main = "src/index.js"
compatibility_date = "2026-06-25"

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = [ "/", "/api/*", "/admin", "/admin/*", "/group/*" ]
html_handling = "none"
not_found_handling = "none"

[[d1_databases]]
binding = "DB"
database_name = "bale_checker_db"
database_id = "378ccadb-30f9-4871-8145-4b008f012208"
